### ISSUE TITLE
Invalid MD5/SHA for many hosted files

### ISSUE THREAD

**Issue by weirdal3333** [THZoria/NX_Firmware#1]
When compared to the official zips, MANY of your files are corrupted or incomplete.

For example:
![image](https://user-images.githubusercontent.com/3537180/236699152-b49ff331-654f-47b2-a2b1-fedb8cf41aa2.png)

Please verify your files!

**Comment by PoloNX** [comment]
I tried to update it after your issue from the homebrew AtmoPackUpdater which takes the firmware here and it works fine. It’s weird

**Comment by THZoria** [comment]
Normal, I don't dump my archives I download the ncas from the Nintendo servers
They are not corrupted because tested before release on emulator and on Switch via Daybreak
![image](https://user-images.githubusercontent.com/50277488/236699945-28426367-2a69-40f6-a349-a0c5034b0761.png)
![image](https://user-images.githubusercontent.com/50277488/236699949-704bee10-a364-4ba5-a7f9-93eb7cfbec64.png)

**Comment by impeeza** [comment]
all checksum are valid with the scene datfiles:
https://gbatemp.net/download/nintendo-switch-firmware-datfile.36558/updates#resource-update-39574

**Comment by weirdal3333** [comment]
Huh that's really weird. I redownloaded the zip with jdownloader2 this time and the checksums are all correct now.
Must've been download corruption or something.
